/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Accounts
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Twilio.Rest.Api.V2010.Account.Call
{

    public class CreateFeedbackCallSummaryOptions : IOptions<FeedbackCallSummaryResource>
    {
        // How to decide which has getter and which has setter ?
        
        public DateTime? EndDate { get; set; }
        public DateTime? StartDate { get; set; }
        public string PathAccountSid { get; set; }

        /// <summary>
        /// Construct a new CreateCallFeedbackSummaryOptions
        /// </summary>
        /// <param name="endDate">  </param>
        /// <param name="startDate">  </param>

        public CreateFeedbackCallSummaryOptions(DateTime? endDate, DateTime? startDate)
        {
            EndDate = endDate;
            StartDate = startDate;
        }
    }
}

