/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Accounts
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Twilio.Rest.Api.V2010.Account
{

    public class CreateCallOptions : IOptions<CallResource>
    {
        // How to decide which has getter and which has setter ?
        
        public string RequiredStringProperty { get; set; }
        public string PathAccountSid { get; set; }
        public List<string> TestArrayOfStrings { get; set; }

        /// <summary>
        /// Construct a new CreateCallOptions
        /// </summary>
        /// <param name="requiredStringProperty">  </param>

        public CreateCallOptions(string requiredStringProperty)
        {
            RequiredStringProperty = requiredStringProperty;
            TestArrayOfStrings = new List<string>();
        }
    }

    public class DeleteCallOptions : IOptions<CallResource>
    {
        
        ///<summary>
        /// INTEGER ID param!!!
        ///</summary>
        public int PathTestInteger { get; set; }
        public string PathAccountSid { get; set; }


        /// <summary>
        /// Construct a new DeleteCallOptions
        /// </summary>
        /// <param name="pathTestInteger"> INTEGER ID param!!! </param>

        public DeleteCallOptions(int pathTestInteger)
        {
            PathTestInteger = pathTestInteger;
        }
    }



    public class FetchCallOptions : IOptions<CallResource>
    {
    
        ///<summary>
        /// INTEGER ID param!!!
        ///</summary>
        public int PathTestInteger { get; set; }
        public string PathAccountSid { get; set; }


        /// <summary>
        /// Construct a new FetchCallOptions
        /// </summary>
        /// <param name="pathTestInteger"> INTEGER ID param!!! </param>

        public FetchCallOptions(int pathTestInteger)
        {
            PathTestInteger = pathTestInteger;
        }
    }


}

