/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Accounts
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace Twilio.Rest.Api.V2010
{

    public class CreateAccountOptions : IOptions<AccountResource>
    {
        // How to decide which has getter and which has setter ?
        
        public string XTwilioWebhookEnabled { get; set; }
        public Uri RecordingStatusCallback { get; set; }
        public List<string> RecordingStatusCallbackEvent { get; set; }

    }

    public class DeleteAccountOptions : IOptions<AccountResource>
    {
        
        public string PathSid { get; set; }


    }



    public class FetchAccountOptions : IOptions<AccountResource>
    {
    
        public string PathSid { get; set; }


    }



    public class ReadAccountOptions : ReadOptions<AccountResource>
    {
    
        public DateTime? DateCreated { get; set; }
        public DateTime? DateTest { get; set; }
        public DateTime? DateCreatedBefore { get; set; }
        public DateTime? DateCreatedAfter { get; set; }
        public int? PageSize { get; set; }


    }


    public class UpdateAccountOptions : IOptions<AccountResource>
    {
    
        public TestResource.StatusEnum Status { get; set; }
        public string PathSid { get; set; }
        public string PauseBehavior { get; set; }


        /// <summary>
        /// Construct a new UpdateAccountOptions
        /// </summary>
        /// <param name="status">  </param>

        public UpdateAccountOptions(TestResource.StatusEnum status)
        {
            Status = status;
        }
    }


}

